#! /bin/bash

# write ~/.vcrans.gpg
echo "echo '$1' | gpg --decrypt --passphrase-fd 0 '${2}.gpg' > '${2}' && vim '${2}' && echo '$1' | gpg -o '${2}.gpg' --batch --yes --passphrase-fd 0 --cipher-algo AES256 --symmetric '${2}' && rm '${2}'" > ~/.vcrans
echo "$1" | gpg -o ~/.vcrans.gpg --batch --yes --passphrase-fd 0 --cipher-algo AES256 --symmetric ~/.vcrans
rm ~/.vcrans

# write secret file
touch "${2}"
echo "$1" | gpg -o "${2}.gpg" --batch --yes --passphrase-fd 0 --cipher-algo AES256 --symmetric "${2}"

# Write crans file
printf "#! /usr/bin/env bash\n gpg --decrypt '${2}.gpg'" > crans
chmod a+x crans

# Write vcrans file
printf '#! /usr/bin/env bash\neval $(gpg --decrypt ~/.vcrans.gpg)' > vcrans
chmod a+x vcrans

